### ISSUE TITLE
Response Header population inconsistent

### ISSUE THREAD

**Issue by dustensalinas** [Azure/azure-cosmos-js#156] opened 2018-10-09 16:07 UTC
Been trying to track down more details on this one but am pressed for time and replication is odd.

Queries that do not have parameters and do not have specific FeedOptions do not populate Response headers.  Expectation is that headers always are populated in the response.headers.

Example:
`        let querySpec =
        {
            query: "SELECT C.id, C.company_name FROM Customers C"
        };
`
---
` let response = await this.container.items.query(querySpec, options).toArray();`

Cases when response.headers is empty based on options:
`options = {}`
`options = {
            enableCrossPartitionQuery: true,
            populateQueryMetrics: true
}`

Cases when its populated
`
        let options = {
            enableCrossPartitionQuery: true,
            populateQueryMetrics: true,
            maxItemCount: 1 
        }
`
p.s. maxItemCount isnt being respected either but will log a separate issue for that.

Second, if querySpec has params headers are populated.  If querySpec does not have params but the query itself has something like Status = 1, headers populate.

**Comment by dustensalinas** [comment] 2018-10-09 16:14
New finding:
`let options = { enableCrossPartitionQuery: true, populateQueryMetrics: true, maxItemCount: 1000 }`, ie population in excess of total results returns undefined headers.

**Comment by southpolesteve** [comment] 2018-10-15 19:54
@dustensalinas Thanks for the report. This has come up before and it is something we do need to fix. The issue is similar to #157 in that toArray() can result in many calls to the server. If you are looking for granular metrics, your best bet is to step through the calls yourself using methods on `QueryIterator` like `executeNext()` or `getAsyncIterator()`. Those return headers for each request. I'm going to leave this open while I discuss with the team the best way to report headers/metrics(https://github.com/Azure/azure-cosmos-js/issues/75) on toArray() results.

**Comment by dustensalinas** [comment] 2018-12-21 17:09
I've now run across this bug/enhancement in another project and got me thinking about it again.  I think the real difficulty here is the inconsistency (ie if only one query was called then it populates vs not).  Might I suggest the response headers be populated in an array?  This way no odd transformations but if we call something like toarray and multiple requests were needed to populate it, we know that there are multiple headers and can address appropriately vs sometimes there and sometimes undef?

**Comment by southpolesteve** [comment] 2019-03-21 23:23
We're aiming to have this working with a rolled up proper response object in v3

**Comment by christopheranderson** [comment] 2019-08-20 04:00
This is (somewhat) resolved in V3. There are still some differences in behavior between defaultQEC and pipelinedQEC (like continuation token support). Out of scope for this issue, so resolving as solved.

**Closed by christopheranderson** 2019-08-20 04:00 UTC
Labels: bug, v3
